global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'collector'
    honor_timestamps: true
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['collector:8889']
      - targets: ['collector:8888']
